// MERN/day11/merningWithBooksIII/front/src/components/NavBar.jsx
import React from 'react'
import { Link } from 'react-router-dom'

const NavBar = ({page, pageSetter}) => {
    
  return (
      <div className=' bg-green-200 min-w-dvw flex items-center p-5 justify-between'>
          <ul className=' flex gap-5'>
              <li><Link to={'/'} onClick={()=>pageSetter('Book Catalog')} className=' bg-amber-200 p-1 rounded-lg border'>Book Catalog</Link></li>
              <li><Link to={'/create'} onClick={()=>pageSetter('Create Book')} className=' bg-blue-500 text-white rounded-lg p-1 border border-black'>Create Book</Link></li>
          </ul>
          <h1 className=' text-3xl text'> {page} </h1>
    </div>
  )
}

export default NavBar

// Angular/day3/booksAngular/client/src/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {

}

<div class=" border  p-5 flex gap-5 rounded-lg bg-gray-200">
  <a routerLink="/" class=" border text-white bg-blue-500 rounded-lg p-1 border-blue-500">home</a>
  <a routerLink="/create" class=" border rounded-lg bg-green-500 text-white border-green-500 p-1">create</a>
</div>
