// Angular/day3/booksAngular/client/src/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {

}

<div class=" border  p-5 flex gap-5 rounded-lg bg-gray-200">
  <a routerLink="/" class=" border text-white bg-blue-500 rounded-lg p-1 border-blue-500">home</a>
  <a routerLink="/create" class=" border rounded-lg bg-green-500 text-white border-green-500 p-1">create</a>
</div>

// MERN/dat13/client/src/components/Navbar.jsx
import React from "react";
import { Link } from "react-router-dom";

const Navbar = ({ page, setPage }) => {
  return (
    <div className="flex p-1 border rounded-lg justify-around">
      <Link
        to={"/"}
        className={` ${
          page === "Home" ? "bg-blue-100" : "bg-white"
        }  px-3 py-2 rounded-md`}
        onClick={() => setPage("Home")}
      >
        Home
      </Link>
      <Link
        to={"/create"}
        className={` ${
          page === "Create" ? "bg-blue-100" : "bg-white"
        }  px-3 py-2 rounded-md`}
        onClick={() => setPage("Create")}
      >
        Create Post
      </Link>
    </div>
  );
};

export default Navbar;
